defaults: &defaults
  after_authorize: "/wechat/home"
  tmp_media_expire_time: 3.days 

development:
  <<: *defaults
  website_url: "http://ads.sensetime.com"

test:
  <<: *defaults

production:
  <<: *defaults
  website_url: "http://ads.sensetime.com"
